config/routes.rb
Rails.application.routes.draw do
  
  #Redefinir senha controller
  get 'redefinir_senha/busca', to: "redefinir_senha#busca", as: :redefinir_senha
  post 'redefinir_senha/busca', to: "redefinir_senha#recuperar"

  resources :comentarios
  resources :posts
  root to: "sessoes#new"
  get 'login', to: "sessoes#new", as: :login
  post 'login', to: "sessoes#create"
  delete 'logout', to: "sessoes#destroy", as: :logout
  get 'feed', to: "posts#feed", as: :feed

  resources :usuarios

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :categorium, foreign_key: "categoria_id"
  has_many :comentarios
  belongs_to :usuario
  mount_uploader :avatar, AvatarUploader

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :usuario_nao_logado
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  #GET feed
  def feed
    @post = Post.new
    @posts = Post.all.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 2)
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comentario = Comentario.new
    @comentarios = @post.comentarios
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:usuario_id, :titulo, :conteudo, :avatar, :categoria_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag "post[usuario_id]", current_user.id %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, id: :post_titulo %>
  </div>
  
  <%= form.label "Categoria" %>
    <%= select("post", "categoria_id", Categorium.all.collect {|categorium| [ categorium.nome,
      categorium.id ] }, {include_blank: "Categoria"}, id: :categorium) %>
    <br>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_field :conteudo, id: :post_conteudo %>
  </div>

  	<div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/feed.html.erb
<h1>Feed de Notícias</h1>

<%= render "form", post: @post %>

<% @posts.each do |post| %>
  <h2><%= link_to post.titulo, post_path(post) %></h2>


  <% if !post.avatar.file.nil? %>
    <%= image_tag post.avatar.thumb.url %>	
  <% end %>
  <p><%= post.conteudo %></p>
  <% @post = post %>


  <p>Escrito por <%= link_to @post.usuario.nome, usuario_path(id: current_user.id) %></p>

  
  <% if current_user == post.usuario %>
    <p><%= link_to "Editar", edit_post_path(post) %></p>
  <% end %>
  
  <br>

<% end %>

<%= will_paginate @posts %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Titulo</th>
      <th>Conteudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.usuario.nome %></td>
        <td><%= post.titulo %></td>
        <td><%= post.conteudo %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
  
</p>


<% if !@post.avatar.file.nil? %>
  <%= image_tag @post.avatar.thumb.url %>
<% end %>
<p>
  <strong>Usuario:</strong>
  <%= link_to @post.usuario.nome, usuario_path(id: current_user.id) %>
</p>
<p>
  <strong>Categoria:</strong>
  <%=  @post.categorium.nome %>
</p>



<p>
  <strong>Conteudo:</strong>
  <%= @post.conteudo %>
</p>

<p>
  <%= render "comentarios/form", comentario: @comentario %>
</p>

<% @comentarios.each do |comentario| %>
  <p><%= comentario.conteudo %></p>
<% end %>
<br>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>